export { default as candlebright_blue } from './candlebright_blue.svg'
export { default as candlebright_green } from './candlebright_green.svg'
export { default as candlebright_purple } from './candlebright_purple.svg'
export { default as candlebright_red } from './candlebright_red.svg'
export { default as candlebright_yellow } from './candlebright_yellow.svg'

export { default as laser_burst_blue } from './laser_burst_blue.svg'
export { default as laser_burst_green } from './laser_burst_green.svg'
export { default as laser_burst_purple } from './laser_burst_purple.svg'
export { default as laser_burst_red } from './laser_burst_red.svg'
export { default as laser_burst_yellow } from './laser_burst_yellow.svg'